# _config.yml
title: Maria Dumitrescu
description: UI UX Designer Portfolio
url: "https://mariadumitrescu.art" # the base hostname & protocol for your site
github_username: yourusername
permalink: pretty